### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._internal.download'

### ISSUE THREAD

**Issue by shimachao** [sqreen/PyMiniRacer#102]
I try to install  PyMiniRacer on windows 10.

pip install py-mini-racer
Looking in indexes: https://pypi.douban.com/simple
Collecting py-mini-racer
  Using cached https://pypi.doubanio.com/packages/25/79/e158bbf5a2bbcdf990738566653d8caa8bc612007d4c0ed319bb3803a832/py_mini_racer-0.1.18.tar.gz (330 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\chengnan\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chengnan\\AppData\\Local\\Temp\\pip-install-bxfjy60h\\py-mini-racer\\setup.py'"'"'; __file__='"'"'C:\\Users\\chengnan\\AppData\\Local\\Temp\\pip-install-bxfjy60h\\py-mini-racer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\chengnan\AppData\Local\Temp\pip-install-bxfjy60h\py-mini-racer\pip-egg-info'
         cwd: C:\Users\chengnan\AppData\Local\Temp\pip-install-bxfjy60h\py-mini-racer\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\chengnan\AppData\Local\Temp\pip-install-bxfjy60h\py-mini-racer\setup.py", line 58, in <module>
        requirements = _parse_requirements('requirements/prod.txt')
      File "C:\Users\chengnan\AppData\Local\Temp\pip-install-bxfjy60h\py-mini-racer\setup.py", line 44, in _parse_requirements
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### System configuration
**PyMiniRacer version**:0.1.18

**Python version**:3.7.6

**Comment by nizox** [comment]
The issue was fixed with https://github.com/sqreen/PyMiniRacer/commit/15bf2f61976ebe2a6861c33b1498ddf8733acb1e. It should work fine with the latest 0.2 version. Sorry for the inconvenience.
