### ISSUE TITLE
linux killed process

### ISSUE THREAD

**Issue by lirifei** [sqreen/PyMiniRacer#107]
\var\log\messages
Jun  9 10:23:05 centos7.7 kernel: gunicorn[4541]: segfault at 7ffea55d2ff8 ip 00007fa9ccbda878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9cca0d000+942000]
Jun  9 10:33:12 centos7.7 kernel: gunicorn[6215]: segfault at 7ffea55d2ff8 ip 00007fa9cc4eb878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9cc31e000+942000]
Jun  9 10:42:38 centos7.7 kernel: gunicorn[7183]: segfault at 7ffea55d2ff8 ip 00007fa9c9a9f878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c98d2000+942000]
Jun  9 10:53:39 centos7.7 kernel: gunicorn[8174]: segfault at 7ffea55d2ff8 ip 00007fa9ccbda878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9cca0d000+942000]
Jun  9 11:03:58 centos7.7 kernel: gunicorn[9324]: segfault at 7ffea55d2ff8 ip 00007fa9ca0e0878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c9f13000+942000]
Jun  9 11:12:55 centos7.7 kernel: gunicorn[10277]: segfault at 7ffea55d2ff8 ip 00007fa9c503a878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c4e6d000+942000]
Jun  9 11:23:06 centos7.7 kernel: gunicorn[11092]: segfault at 7ffea55d2ff8 ip 00007fa9c999f878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c97d2000+942000]
Jun  9 11:32:14 centos7.7 kernel: gunicorn[12029]: segfault at 7ffea55d2ff8 ip 00007fa9c915e878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c8f91000+942000]
Jun  9 11:42:05 centos7.7 kernel: gunicorn[13068]: segfault at 7ffea55d2ff8 ip 00007fa9c909e878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c8ed1000+942000]
Jun  9 11:53:11 centos7.7 kernel: gunicorn[14018]: segfault at 7ffea55d2ff8 ip 00007fa9c3036878 sp 00007ffea55d3000 error 6 in _v8.so[7fa9c2e69000+942000]

### System configuration
**centos version**:
7.7
**PyMiniRacer version**:
0.2.0
**Python version**:
3.6.8

**Comment by nizox** [comment]
Hello! A new version of PyMiniRacer (0.6.0) was released with a fix for a crash which happen during MiniRacer shutdown phase. I am closing this issue but let us know if the issue persists.
