### ISSUE TITLE
[Question] Safe to run untrusted code?

### ISSUE THREAD

**Issue by ColdHeat** [sqreen/PyMiniRacer#118]
Thanks for this really good library! Sorry if this isn't the right place for questions.

I couldn't find a definite answer for this but is it safe to run untrusted code in `py_mini_racer.MiniRacer()` or `py_mini_racer.StrictMiniRacer()`? 

With the timeout and memory limit kwargs it seems like that concern is handled and v8 itself I don't believe provides the ability to access the network or disk. Just want to ask if perhaps this already used by sqreen for sandboxing purposes? 

Thanks again!

**Comment by nizox** [comment]
The difference between `py_mini_racer.MiniRacer()` and `py_mini_racer.StrictMiniRacer()` lies in the fact that the former serialises Javascript objects with a custom binary format while the later uses JSON. The custom serialisation code is not covered by the memory and timeout limits but JSON is.

Sqreen uses `py_mini_racer` to run trusted code only but indeed, it also provides some nice sandboxing properties like no access to network or disk. However, please keep in mind that `py_mini_racer` sandboxing relies uniquely on V8 and that any vulnerability found in V8 can be used to escape it.

**Comment by ColdHeat** [comment]
I understand the ramifications of just using v8 for sandboxing and I think `py_mini_racer` will work well for my needs. 

Thanks again for answering my questions and maintaining the project!
