### ISSUE TITLE
How to make it runs on PyPy

### ISSUE THREAD

**Issue by Infixz** [sqreen/PyMiniRacer#124]
my python app runs on PyPy and it need a js runtime, is it possible to make mini racer runs on pypy.

**Comment by nizox** [comment]
Hi, thanks for your interest in PyMiniRacer. Even if we don't mention it on the front page of the project, you should be able to use PyMiniRacer on PyPy. You can install it with `pip install py-mini-racer` on your PyPy virtualenv.
