### ISSUE TITLE
RuntimeError: Native library not available at ......site-packages/py_mini_racer/libmini_racer.dylib

### ISSUE THREAD

**Issue by JesseLT** [sqreen/PyMiniRacer#126]
I'm using Macbook Air M1,and I install `py-mini-racer` with pip successfully.but when I run `ctx = py_mini_racer.MiniRacer()` the error `RuntimeError: Native library not available at /Users/dmitry/Applications/Miniforge3/envs/python38/lib/python3.8/site-packages/py_mini_racer/libmini_racer.dylib` happens. I have checked the directory, there is no file named libmini_racer.dylib.
I have no idea about that.Can anyone help? Grateful!
 file `which python`
/Users/dmitry/Applications/Miniforge3/envs/python38/bin/python: Mach-O 64-bit executable arm64

python -V
Python 3.8.6

**Comment by cbc009** [comment]
> I'm using Macbook Air M1,and I install `py-mini-racer` with pip successfully.but when I run `ctx = py_mini_racer.MiniRacer()` the error `RuntimeError: Native library not available at /Users/dmitry/Applications/Miniforge3/envs/python38/lib/python3.8/site-packages/py_mini_racer/libmini_racer.dylib` happens. I have checked the directory, there is no file named libmini_racer.dylib.
> I have no idea about that.Can anyone help? Grateful!
> file `which python`
> /Users/dmitry/Applications/Miniforge3/envs/python38/bin/python: Mach-O 64-bit executable arm64
> 
> python -V
> Python 3.8.6

哥，咋解决的呀
