### ISSUE TITLE
ImportError: cannot import name 'MiniRacer'

### ISSUE THREAD

**Issue by RussiaVk** [sqreen/PyMiniRacer#134]
```
 Traceback (most recent call last):
  File "C:\Users\RUSSIAVK\Desktop\hello.py", line 2, in <module>
    from py_mini_racer import MiniRacer
ImportError: cannot import name 'MiniRacer'
```

**Comment by RussiaVk** [comment]
should be 
`from py_mini_racer import py_mini_racer`

**Comment by DeadWisdom** [comment]
Sorry I don't have time to make a PR, but your README says:

    from py_mini_racer import MiniRacer

But you have to do:

    from py_mini_racer.py_mini_racer import MiniRacer
