### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by 77cc33** [sqreen/PyMiniRacer#14]
Hello,

We are using V8 to convert saved JS generated objects (dictionaries) with sensitive data to python objects, as it much faster than other ways we tried. Our dictionaries usually have at least 2000-3000 elements.

We tried different libraries to take benchmarks what are all based on different V8 versions. Your library is very easy to install and use, but it's 10 times slower than PyV8 in our case. Do you have some ideas how to improve this speed?

Here are bench results for your lib and PyV8 https://github.com/qistoph/pyv8 (what has best performance), we also tried v8eval (it has a little faster speed than you have) and  v8 cliff https://pypi.python.org/pypi/v8-cffi - this library has the same as PyV8 performance, but it returns all time strings (so no object conversion)

Here is code we used, with "a" variable as 2K elements JS dictionary. 

**PyV8**

``` python
import PyV8
ctxt = PyV8.JSContext()
ctxt.enter()
t = time.time()
ctxt.eval(a)
print(time.time() - t)
```

**Time Taken:** 0.0019199848175

**PyMiniRacer**

``` python
from py_mini_racer import py_mini_racer
ctx = py_mini_racer.MiniRacer()
t = time.time()
ctx.eval(a)
print(time.time()-t)
```

**Time Taken:** 0.0178089141846

The only difference in results, is that you returns python Dict, and PyV8 returns JSObject (what is like Python object).
### Expected behavior

Faster Speed
### Actual behavior

Slower speed :-)
### System configuration

**PyMiniRacer version**:
Latest one

**Python version**:
Python 2.7.12

**Comment by aviat** [comment]
HI,

Thanks for your feedback.

Our use case is quite different from yours, and we focused on optimizing performance in this goal (as you can see with the recent pull request #10).

Our use case is the following: 
 - at startup, we initialize a context with JS code once (and then we keep it around for a very long time);
 - very often, we call the code of this context a lot - that’s the part we need to be fast.

Our use case also make us use very tiny objects in output, so we did not reach your use case of working with large arrays.

What might fasten your particular use case is to do:
 - in JS: `JSON.stringify(your_js_object)`
 - in Python: `json.loads(the_returned_value)` 

I’ll be glad to discuss it further if you had any idea to optimize PyMiniRacer for your use case.

**Comment by uranusjr** [comment]
Just throwing out wild ideas here, but maybe ctypes is causing a lot of the difference here? It is known to be very slow compared to a C extension like PyV8. Maybe [cffi](http://cffi.readthedocs.io/en/latest/) would close some gap.

**Comment by aviat** [comment]
Hi @uranusjr, yes cffi could be a good choice. We didn't used it at the time, the manylinux wheels were not available at the time - and setup ease is a key requirement for PyMiniRacer.
Would be interested in discussing this further?
