### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by wangtubs** [sqreen/PyMiniRacer#15]
Python version: 2.7
pip version 8.1.2
I try to install pyminiRacer through pip install py-mini-racer
I get error like this

>     Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
>                 To update pip: 'pip install -U pip'
>                 See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
> 
>                 Original error: WindowsError(2, '')
> 
>     ----------------------------------------
> Command "c:\python27\python.exe -u -c "import setuptools, 

> tokenize;__file__='c:\\users\\will\\appdata\\local\\temp\\pip-build-gt42mx\\py-mini-racer\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\will\appdata\local\temp\pip-yekl1e-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\will\appdata\local\temp\pip-build-gt42mx\py-mini-racer\

I don't know if you need addtional dependence for this package.

**Comment by wangtubs** [comment]
on ubuntu 14 I get error also:
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability

                Original error: WindowsError(2, '')

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\will\\appdata\\local\\temp\\pip-build-gt42mx\\py-mini-racer\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\will\appdata\local\temp\pip-yekl1e-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\will\appdata\local\temp\pip-build-gt42mx\py-mini-racer\

**Comment by aviat** [comment]
Hi @wangtubs, the error you pasted seems to be on Windows. PyMiniRacer is not tested under Windows.
Yet, Ubuntu should work fine. Could you try to upgrade your pip version:
`pip install -U pip`
and then try to install PyMiniRacer again?

**Comment by wangtubs** [comment]
ubuntu also doesn't work for me . pip is 1.5.1 version.

**Comment by aviat** [comment]
@wangtubs could you please give me the output of these commands?
```
$ pip install -U pip
$ pip --version
```

**Comment by wangtubs** [comment]
root@hi:~# pip install -U pip
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

root@hi:~# pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by aviat** [comment]
@wangtubs awesome, now you have the correct pip version. You can now just try:

```
$ pip --version
$ pip install py-mini-racer
```

**Comment by wangtubs** [comment]
thanks. it works now.  
I have another questions now. I want to use your package to run js . but the js needs to do something with dom.  is there any way to use your package to run js without exception?
for now there is error when i run the js script:
  File "/usr/local/lib/python2.7/dist-packages/py_mini_racer/py_mini_racer.py", line 120, in eval
    python_value = res.contents.to_python()
  File "/usr/local/lib/python2.7/dist-packages/py_mini_racer/py_mini_racer.py", line 217, in to_python
    raise JSEvalException(msg.decode('utf-8', errors='replace'))
py_mini_racer.py_mini_racer.JSEvalException: ReferenceError: window is not defined
ReferenceError: window is not defined
    at eval (eval at _h (unknown source), <anonymous>:4:4)
    at eval (eval at _h (unknown source), <anonymous>:35:3)
    at _h (<anonymous>:5:16)
    at eval (eval at _h (unknown source), <anonymous>:8:4)
    at _h (<anonymous>:5:16)
    at <anonymous>:16:2

**Comment by wangtubs** [comment]
the js script now is actually a encrypt script, i want to use your package to descrypt the script and get the data after running the js. actually I don't need it to handle the DOM.

**Comment by aviat** [comment]
So we are good @wangtubs ?

**Comment by wangtubs** [comment]
@aviat you have not answered my new question.  so your package can't do with DOM?

**Comment by aviat** [comment]
You need a browser to do DOM. We only provide a bare metal JavaScript environment.

**Comment by wangtubs** [comment]
Hi, I actually don't want to handle the DOM. I want to use your package to decrypt a js script. the js script is very complicate.  What I mean is to run the js script with your package, and I want get the data after running. but currently your package will go error because the script try to handle DOM. is there any way to stop the script and output the result before it handles DOM?

**Comment by aviat** [comment]
Yes, you need to modify your script.

**Comment by wangtubs** [comment]
```
from requests import Request, Session
import re
s = Session()
data = {"sf_url":"https://www.youtube.com/watch?v=EOL4HG2gOZQ","new":"1","lang":"en"}
headers ={"Content-Type":"application/x-www-form-urlencoded",
           "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
           "Referer":"http://en.savefrom.net/",
           "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
           "Accept-Encoding:":"gzip, deflate",
           "Accept-Language":"en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,ar;q=0.2,zh-TW;q=0.2",
           "Cache-Control":"max-age=0",
           }
url = 'http://en.savefrom.net/savefrom.php'
cookie = {'lang':'en','uid':'dbdf4bbfa65c0a91','PHPSESSUD':'2e5f1f66946dedfa07992d1c47094cde','uid':'dbdf4bbfa65c0a91','_ga':'GA1.2.522510002.1477312812'}
req = Request('POST', url, data=data, headers=headers,cookies=cookie)
prepped = req.prepare()
resp = s.send(prepped)

res = resp.content
print res
y= res[57:-29]
# print y
from py_mini_racer import py_mini_racer
ctx = py_mini_racer.MiniRacer()
ctx.eval(y)
```
hi, there is my script, but now it give error when it try to handle DOM
can you help me to modify the script? 
I tried many methods, always not successful.
thanks very much

**Comment by Nambers** [comment]
> ```
> from requests import Request, Session
> import re
> s = Session()
> data = {"sf_url":"https://www.youtube.com/watch?v=EOL4HG2gOZQ","new":"1","lang":"en"}
> headers ={"Content-Type":"application/x-www-form-urlencoded",
>            "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
>            "Referer":"http://en.savefrom.net/",
>            "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
>            "Accept-Encoding:":"gzip, deflate",
>            "Accept-Language":"en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,ar;q=0.2,zh-TW;q=0.2",
>            "Cache-Control":"max-age=0",
>            }
> url = 'http://en.savefrom.net/savefrom.php'
> cookie = {'lang':'en','uid':'dbdf4bbfa65c0a91','PHPSESSUD':'2e5f1f66946dedfa07992d1c47094cde','uid':'dbdf4bbfa65c0a91','_ga':'GA1.2.522510002.1477312812'}
> req = Request('POST', url, data=data, headers=headers,cookies=cookie)
> prepped = req.prepare()
> resp = s.send(prepped)
> 
> res = resp.content
> print res
> y= res[57:-29]
> # print y
> from py_mini_racer import py_mini_racer
> ctx = py_mini_racer.MiniRacer()
> ctx.eval(y)
> ```
> 
> hi, there is my script, but now it give error when it try to handle DOM
> can you help me to modify the script?
> I tried many methods, always not successful.
> thanks very much

Oh hi, i am amazing that we meet the same problem in a similar problem
today i am trying to answer this question "https://stackoverflow.com/questions/65443895/how-to-input-data-via-a-post-request-using-requests-in-python/65650186#65650186", and it also for the downloading of youtube lol
So, do you find the solution?
