### ISSUE TITLE
Passing non-primitive objects

### ISSUE THREAD

**Issue by uranusjr** [sqreen/PyMiniRacer#17]
In V8 you can pass a C++ function into the JavaScript context, to use as a callback etc. It would be very useful if this can be exposed to MiniRacer. The current implementation of `call` relies on `json.dumps`, so a more sophisticated bridging method would be required.

**Comment by aviat** [comment]
Hi @uranusjr, that's a good idea. Would like to propose such an implementation?

**Comment by uranusjr** [comment]
Sure, I am not familiar with V8’s API, but Qt exposes something similar in [QJSEngine](http://doc.qt.io/qt-5/qjsengine.html), which is (IIRC) also based on V8, to work with arbitrary Qt objects. I’ll take a look at their implementation.
