### ISSUE TITLE
Changes in libv8's builder.rb file since Oct 2016

### ISSUE THREAD

**Issue by ignisf** [sqreen/PyMiniRacer#24]
Hi,

Just a heads up -- I've updated a few things since you last touched your `v8_build.py`. Check out https://github.com/cowboyd/libv8/compare/d64aebf6c53b7402241b1c769299902ebe1a7bd3...master#diff-aec54aa0f7e48aa0b8c39b9d58825419 (important changes are in `builder.rb` and an additional patch to prevent debugging being included in macOS binaries)

**Comment by aviat** [comment]
Thanks a lot @ignisf we have quite changed the way we build PyMiniRacer.
