### ISSUE TITLE
Is it possible to invoke provided Python functions in the JS script?

### ISSUE THREAD

**Issue by maurocchi** [sqreen/PyMiniRacer#25]

**Comment by aviat** [comment]
Hi @maurocchi, this feature is not implemented in PyMiniRacer yet. Would you be interested in contributing?

**Comment by maurocchi** [comment]
Hi Jean-Baptiste, currently I'm still in explorative mode, however thanks for the opportunity.

**Comment by btashton** [comment]
I'm starting to dig into how this might be implemented.

**Comment by aviat** [comment]
Hey @btashton, any news on this?

**Comment by aviat** [comment]
@maurocchi closing since no news from you. Let me know if you need any pointer on this!

**Comment by nevros** [comment]
https://github.com/tbodt/v8py/blob/4fe3eea9ac637e8dba365f215498a2f8fafd0c45/v8py/convert.cpp#L11

it has been implemented in this project, so that could be used as a reference point
