### ISSUE TITLE
py_mini_racer module not loading on Ubuntu 14

### ISSUE THREAD

**Issue by ljgww** [sqreen/PyMiniRacer#26]
### Steps to reproduce
	:~/dev/py-code/pyJS$ sudo -H pip install py_mini_racer
	Collecting py_mini_racer
	  Using cached py_mini_racer-0.1.10-cp27-cp27m-manylinux1_x86_64.whl
	Requirement already satisfied: enum34 in /usr/local/lib/python2.7/site-packages (from py_mini_racer)
	Installing collected packages: py-mini-racer
	Successfully installed py-mini-racer-0.1.10

	:~/dev/py-code/pyJS$ python
	Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
	[GCC 4.8.4] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import py_mini_racer
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	ImportError: No module named py_mini_racer
	>>> 

### Expected behavior
to be able to use it

### Actual behavior
module not loading

### System configuration
**PyMiniRacer version**: see above

**Python version**:
        $ python --version
        Python 2.7.6
        $ uname -a
        Linux haarp 3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64 x86_64 6
        x86_64 GNU/Linux
        Ubuntu 14.04

**Comment by Lothiraldan** [comment]
Hi @ljgww, could you paste the output of `python -c "import sys; print(sys.path)"` to check that your python is looking at the right places?

**Comment by aviat** [comment]
No answer, closing.

**Comment by ljgww** [comment]
sorry for taking time to come back. Will try the library with some more recent installation of python.

Sys.path

$ python -c "import sys; print(sys.path)"
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/lj/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode']

Now. I had similar issues with a number of python packages and it turns out that system python path is not taking in account some of custom paths (or taking some user related paths) made by other versions of python that I run. Running multiple pythons on Ubuntu can get messy.

Major problem is that Ubuntu keeps pretty old version of Python as it systemic python (which does not look to me it will be pushed upwards for some time if ever). In order to run some of packages I need more recent version. For some historical reasons there are two additional pythons that I run with additional paths.

What I will try with mini racer is to run it in some newer environment. Not sure where it went but will try to locate its installation.

**Comment by ljgww** [comment]
$ /usr/local/bin/python2.7
    Python 2.7.13 (default, Jul 30 2017, 14:01:53) 
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import py_mini_racer
    >>> 

As I suspected, everything works well with some recent installation
