### ISSUE TITLE
Cannot pip install on Gentoo (x86_64)

### ISSUE THREAD

**Issue by zetaben** [sqreen/PyMiniRacer#3]
Hello guys,

When I tried installing on my Gentoo (which has both py2 & py3) the pip install fails when fetching v8
```
File "/tmp/pip_build_zeta/py-mini-racer/vendor/depot_tools/fetch.py", line 63
   print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^

SyntaxError: invalid syntax  
```

Here is my [pip.log.txt](https://github.com/sqreen/PyMiniRacer/files/397223/pip.log.txt)
and pip/python/uname versions
```
$ pip --version
pip 1.5.6 from /usr/lib64/python3.4/site-packages (python 3.4)
$ pip2.7 --version
pip 1.5.6 from /usr/lib64/python2.7/site-packages (python 2.7)
$ python --version
Python 3.4.3
$ python2.7 --version
Python 2.7.10
```

**Comment by aviat** [comment]
Thanks @zetaben we will take a look.

**Comment by ianjosephwilson** [comment]
I successfully installed it into a virtualenv on gentoo x86_64 with:
```
virtualenv -p python2.7 --no-site-packages ve
# My virtualenv/pip always lags so I upgrade it everytime.
ve/bin/pip install --upgrade pip
ve/bin/pip install py-mini-racer
```

That syntax error looks like a standard python3 syntax error for using print as a statement instead of a function.  Maybe try specifying the python binary to use in a virtualenv and see if that works.

Also your pip looks pretty old, maybe try upgrading it?
```
ian ~/workspace/v8test $ ve/bin/pip --version
pip 8.1.2 from /home/ian/workspace/v8test/ve/lib/python2.7/site-packages (python 2.7)
ian ~/workspace/v8test $ pip --version
pip 7.1.2 from /usr/lib64/python2.7/site-packages (python 2.7)
```

**Comment by Lothiraldan** [comment]
@zetaben Thank you for the report, several things here:
- Your pip version is old, it will not be able to use the precompiled wheel, could you try upgrading it?
- As you cannot use the wheel, your pip is trying to fetch V8, compile V8 and compile py_mini_racer with your default python which is python3. Unfortunately the google helper we use is not compatible with python3, we will try to fix it in the next version.

**Comment by zetaben** [comment]
I only needed to update my pip in the end ! Thanks guys.
