### ISSUE TITLE
Possible to load an external library?

### ISSUE THREAD

**Issue by jwhendy** [sqreen/PyMiniRacer#41]
Hello,

My apologies if this is not the right place; I didn't see a mailing list and the main hit I get is the [intro blog post](https://blog.sqreen.io/embedding-javascript-into-python/) which didn't seem the best, either.

To try and keep it brief, there's [a desire](https://community.plot.ly/t/use-plotly-offline-to-save-chart-as-image-file/408) to export image files from `plotly` without having to go through their servers. The functionality exists in their library, but one has to open the `.html` in a browser to trigger the `downloadImage()` function.

Due to this, solutions are somewhat hokey, relying on `selenium` and `phantomjs` to fake a browser session and either screenshot the page or trigger the download. I'm wondering if `py_mini_racer` would allow for calling the `js` code directly without having to do this.

I'm a `python` noob, and even more so for `js`. I *think* what I'm asking is, "Can I do the equivalent of this with `py_mini_racer`"?
```
<head>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
```

Then, I could do something [like this](https://plot.ly/javascript/getting-started/), replicating what would normally be inside of `<script>`:
```
ctx.eval("""
Plotly.plot( "div_name", [{
	x: [1, 2, 3, 4, 5],
	y: [1, 2, 4, 8, 16] }], {
	margin: { t: 0 } } );
"""
```

Am I understanding this library correctly?

**Comment by jwhendy** [comment]
In some digging, I just found the `R` package for V8, including [a reference](https://cran.r-project.org/web/packages/V8/vignettes/v8_intro.html) to `ct$source()` which will load an external library. I looked up [that function](https://github.com/jeroen/V8/blob/master/R/V8.R#L142), and to my surprise they're just reading the file and doing `eval()` on the contents!

I could reproduce their `crossfilter` example, but not `plotly`. I thinks it's due to [this](https://github.com/plotly/plotly.js/issues/437):

> plotly.js is browser package, with no intention of working in vanilla node.js.

Maybe this should have been obvious... for any others wondering how to do this, I think it's as simple as just running the file:

```
cf_url = 'https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.min.js'
cf_js = urllib.request.urlopen(cf_url).read().decode('utf-8')

### or read locally
# with open('/path/to/crossfilter.min.js') as f:
#     cf_js = f.read()

ctx = py_mini_racer.MiniRacer()
ctx.eval(cf_js)
```

**Comment by aviat** [comment]
Glad to know it worked, thanks for the heads up @jwhendy.

**Comment by anentropic** [comment]
I have basically the same question, but how to load an npm module

I will try downloading it manually and `eval` the contents 👍

**Comment by anentropic** [comment]
A note to help anyone else in the same boat...

I'm not sure if generally npm modules will work. But fortunately the one I wanted to use also provided a minified version for use in browser.

The module was supposed to export a type `RandExp`, looking at the minified source I could see this at the end:
```js
"function"==typeof define&&"object"==typeof define.amd?define("RandExp",function(){return e}):"undefined"!=typeof window&&(window.RandExp=e)}();
```

Just eval-ing the minified source did not make the code usable in mini racer.

It seems that in v8 we have neither `define` nor `window`. I guess `define.amd` is for node.js usage (and is probably why npm modules won't work) and `window` is expected in browser environment but is `"undefined"` for us.

This was easily worked around though:
```python
from py_mini_racer import py_mini_racer

ctx = py_mini_racer.MiniRacer()

with open("src/randexp.min.js") as f:
    randexp_src = f.read()

ctx.eval("const window = new Object()")
ctx.eval(randexp_src)
ctx.eval("const RandExp = window.RandExp")

ctx.eval("RandExp")
<py_mini_racer.py_mini_racer.JSFunction at 0x10c4ca810>
```
