### ISSUE TITLE
Invoking a function

### ISSUE THREAD

**Issue by alexeygrigorev** [sqreen/PyMiniRacer#53]
### Steps to reproduce

Suppose I have the following code: 

```
code = """
function check() {
    return {
        create: function() {return "create"},
        update: function() {return "update"}
    };
}
"""

ctx = py_mini_racer.MiniRacer()
ctx.eval(code)

check = ctx.execute('check()')
```

Now `check` contains two java script functions:

```
{'create': <py_mini_racer.py_mini_racer.JSFunction at 0x7fe81400c128>,
 'update': <py_mini_racer.py_mini_racer.JSFunction at 0x7fe81448b4a8>}
```

How do I invoke them from python/PyMiniRacer? `ctx.execute(check['create'])` and `ctx.call(check['create']` don't seem to work

### System configuration
**PyMiniRacer version**:

Latest from pip as of 30.05.2018: `py-mini-racer==0.1.14`

**Python version**:
```
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

**Comment by alexeygrigorev** [comment]
As a workaround, I currently do the following:

```
ctx.execute('var tmp = check()')
ctx.call('tmp.create')
ctx.call('tmp.update')
```

Not ideal, but somehow works

**Comment by aviat** [comment]
@alexeygrigorev you could do something similar to this: https://github.com/discourse/mini_racer/pull/80
We would love to get such a contribution!

**Comment by alexeygrigorev** [comment]
Why was it closed? Was the feature added?
