### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by alexeygrigorev** [sqreen/PyMiniRacer#54]
### Steps to reproduce

```
console.log("Hello world");
```

### Expected behavior
It should print "Hello world"

### Actual behavior

```
py_mini_racer.py_mini_racer.JSEvalException: ReferenceError: console is not defined
```

### System configuration
**PyMiniRacer version**: latest from pip

**Python version**: 3.6

**Comment by aviat** [comment]
console is not a JS built-in @alexeygrigorev . A good way to address this would be to allow Python functions to be called from JS. This is not on our roadmap but feel free to contribute!
