### ISSUE TITLE
no way to await async js calls

### ISSUE THREAD

**Issue by fimion** [sqreen/PyMiniRacer#58]
### Steps to reproduce
use this code with your babel transform
```
(function(){
    let thing = new Promise(function(resolve, reject){
                setTimeout(function(){
                    resolve("Done!")
                },1000)
            }),
        result = false;
    thing.then(r=>result=r)
    return result;
})()
```
### Expected behavior
There should be a way to await the promise. maybe this is pipe dream and or i need to compile my own version of babel... but.... it would be useful to have this ability.

### Actual behavior
always returns False

### System configuration
**PyMiniRacer version**:
0.1.15
**Python version**:
3.6

**Comment by fimion** [comment]
that is a fantastic question, and I don't actually have a good answer. since with this specific example you don't have a way to see if the promise has resolved because it's in an anonymous scope.

this may not even be a good example.  currently, if you make a Promise, and that is what miniracer catches, then you would not have a way to check if that promise is done...
i suppose the better way of doing this would be to have a global var called done and to just check that untill everything has resolved?

so i suppose the code would look more like this:
```
var done = false;
var checkDone(){
    return done;
}
(function(){
    let thing = new Promise(function(resolve, reject){
            setTimeout(function(){
                    resolve()
                },1000)
            }),
    thing.then(r=>done=true)
})()
```

then i could simply do a while in python checking checkDone until it's done. that would let the event loop process things right?

**Comment by fimion** [comment]
So, Thinking about this some more... and poking around a bit...

Would it be possible to integrate with this package?

https://pypi.org/project/promise/

if you get a Promise object back, rather than just casting it to an empty object, is it possible to convert it to a python promise?

**Comment by aviat** [comment]
@fimion this is not in our roadmap yet but feel free to contribute @fimion !
