### ISSUE TITLE
Limit resource (execution time and memory usages)

### ISSUE THREAD

**Issue by krukas** [sqreen/PyMiniRacer#63]
Awesome lib and easy to install thanks to the wheels build :smile: . I have a question about limiting resources for the executes Javascript. I want to run user inputted script but want to limit the execution time and memory usages.

What is the best approach to do this, Thanks.

**Comment by aviat** [comment]
Hi @krukas this is not available yet in PyMiniRacer, though we would be more than happy to receive contributions regarding this.
You can find some examples I like here:

- [memory](https://github.com/discourse/mini_racer/blob/master/ext/mini_racer_extension/mini_racer_extension.cc#L724)
 - [timeout](https://github.com/cowboyd/therubyracer/blob/4c2a7449765c61b62c59971b0d3f1e48ded56e0b/ext/v8/script.cc#L88)

Let me know if anything unclear.

**Comment by krukas** [comment]
Hi @aviat, Thanks I'm going to look at it latter, first need to learn some c++ :nerd_face:
