### ISSUE TITLE
new Date().getTime() 

### ISSUE THREAD

**Issue by lirifei** [sqreen/PyMiniRacer#81]
### Steps to reproduce
ctx.eval('new Date().getTime()')

### Expected behavior
Tell us what should happen
1550717977914

### Actual behavior
Tell us what happens instead
1550717977914.0

### System configuration
**PyMiniRacer version**:
0.1.18

**Python version**:
3.6.8

**Comment by nizox** [comment]
PyMiniRacer eval now supports float return type. Thanks for the report.
