### ISSUE TITLE
Segmentation fault on ES6 Symbol evaluation

### ISSUE THREAD

**Issue by noel-smith** [sqreen/PyMiniRacer#82]
### Steps to reproduce
Tested on both Mac + Ubuntu Linux:
```
from py_mini_racer import py_mini_racer
ctx = py_mini_racer.MiniRacer()
ctx.eval('Symbol.toPrimitive')
```

### Expected behavior
Python object representing an ES6 Symbol type should be returned.

### Actual behavior
Segmentation fault generated on Symbol evaluation.

Mac:
```
python3 -c "from py_mini_racer import py_mini_racer; py_mini_racer.MiniRacer().eval('Symbol.toPrimitive')"
Segmentation fault: 11
```
Linux:
```
python3 -c "from py_mini_racer import py_mini_racer; py_mini_racer.MiniRacer().eval('Symbol.toPrimitive')"
Segmentation fault (core dumped)
```

### System configuration
* Mac Mojave 10.14.3
* Ubuntu 18.04.2 LTS

**PyMiniRacer version**:
* py-mini-racer (0.1.18)

**Python version**:
* Mac: Python 3.7.2
* Linux: Python 3.6.7

**Comment by Taiki-San** [comment]
The crash appear to originate from within V8. That's really odd.

**Comment by cataphract** [comment]
I haven't investigated yet, but mini_racer has a similar issue opened: https://github.com/discourse/mini_racer/pull/94
