### ISSUE TITLE
Can you copy a context?

### ISSUE THREAD

**Issue by praguevara** [sqreen/PyMiniRacer#93]
### Steps to reproduce
```
ctx = py_mini_racer.MiniRacer()
ctx2 = deepcopy(ctx)  # or copy(ctx)
```

### Expected behavior
ctx2 is a copy of ctx

### Actual behavior
`ValueError: ctypes objects containing pointers cannot be pickled`

---
I'm sure it's a bit more difficult to copy a whole context than just expecting it to work, but I haven't found a way to do it. Am I doomed to having to create empty contexts or have I missed something?

**Comment by nizox** [comment]
It is not possible to copy a context for now. We could probably implement it by doing a snapshot of the V8 isolate and create a new context with this snapshot. What kind of operations do you want to perform that requires doing a copy of the context?

**Comment by praguevara** [comment]
I had hoped I could do it to perform a MCTS with a simulator written in JS, but to be honest I wouldn't have expected it to be easy.
